// Generated by npm run sync:zhouyi from public/downloads/zhouyi.html.
export function initializeZhouyi(root) {
  const controller = new AbortController();
  const document = {
    body: root,
    getElementById: (id) => root.querySelector(`#${id}`),
    querySelector: (selector) => root.querySelector(selector),
    querySelectorAll: (selector) => root.querySelectorAll(selector),
    addEventListener: (type, listener) => root.addEventListener(type, listener, { signal: controller.signal }),
  };

    "use strict";

    // [原典卦名, 卦辞, 初爻至上爻六条爻辞]
    const HEXAGRAM_TEXTS = {
      1: ["乾","乾，元亨利貞。",["潛龍勿用。","見龍在田，利見大人。","君子終日乾乾，夕惕若，厲无咎。","或躍在淵，无咎。","飛龍在天，利見大人。","亢龍有悔。"]],
      2: ["坤","坤，元亨，利牝馬之貞。君子有攸往，先迷後得，主利，西南得朋，東北喪朋，安貞吉。",["履霜，堅冰至。","直方大，不習无不利。","含章可貞，或從王事，无成有終。","括囊，无咎无譽。","黃裳，元吉。","龍戰于野，其血玄黃。"]],
      3: ["屯","屯，元亨利貞，勿用有攸往，利建侯。",["磐桓，利居貞，利建侯。","屯如邅如，乘馬班如，匪寇婚媾，女子貞不字，十年乃字。","即鹿无虞，惟入于林中。君子幾不如舍。往吝。","乘馬班如，求婚媾，往，吉无不利。","屯其膏，小貞吉，大貞凶。","乘馬班如，泣血漣如。"]],
      4: ["蒙","蒙，亨。匪我求童蒙，童蒙求我。初筮告，再三瀆，瀆則不告。利貞。",["發蒙。利用刑人，用說桎梏，以往吝。","包蒙，吉。納婦吉，子克家。","勿用取女，見金夫，不有躬，无攸利。","困蒙，吝。","童蒙，吉。","擊蒙，不利為寇，利禦寇。"]],
      5: ["需","需，有孚，光亨，貞吉，利涉大川。",["需于郊，利用恒，无咎。","需于沙，小有言，終吉。","需于泥，致寇至。","需于血，出自穴。","需于酒食，貞吉。","入于穴，有不速之客三人來，敬之，終吉。"]],
      6: ["訟","訟，有孚窒惕，中吉終凶。利見大人，不利涉大川。",["不永所事，小有言，終吉。","不克訟，歸而逋其邑，人三百戶，无眚。","食舊德，貞厲，終吉，或從王事，无成。","不克訟，復即命渝，安貞吉。","訟，元吉。","或錫之鞶帶，終朝三褫之。"]],
      7: ["師","師貞，丈人吉，无咎。",["師出以律，否臧凶。","在師中吉，无咎，王三錫命。","師或輿尸，凶。","師左次，无咎。","田有禽，利執言，无咎。長子帥師，弟子輿尸，貞凶。","大君有命，開國承家，小人勿用。"]],
      8: ["比","比吉。原筮元永貞，无咎。不寧方來，後夫凶。",["有孚，比之无咎。有孚盈缶，終來，有它吉。","比之自內，貞吉。","比之匪人。","外比之，貞吉。","顯比，王用三驅，失前禽，邑人不誡，吉。","比之无首，凶。"]],
      9: ["小畜","小畜，亨。密雲不雨，自我西郊。",["復自道，何其咎，吉。","牽復，吉。","輿說輻，夫妻反目。","有孚，血去惕出，无咎。","有孚攣如，富以其鄰。","既雨既處，尚德載，婦貞厲。月幾望，君子征凶。"]],
      10: ["履","履虎尾，不咥人，亨。",["素履，往无咎。","履道坦坦，幽人貞吉。","眇能視，跛能履，履虎尾，咥人凶。武人為于大君。","履虎尾，愬愬，終吉。","夬履，貞厲。","視履，考祥其旋，元吉。"]],
      11: ["泰","泰，小往大來，吉亨。",["拔茅茹，以其彙，征吉。","包荒，用馮河，不遐遺，朋亡，得尚于中行。","无平不陂，无往不復。艱貞无咎。勿恤其孚，于食有福。","翩翩，不富以其鄰，不戒以孚。","帝乙歸妹，以祉元吉。","城復于隍，勿用師。自邑告命，貞吝。"]],
      12: ["否","否之匪人，不利君子貞，大往小來。",["拔茅茹，以其彙，貞吉，亨。","包承，小人吉，大人否亨。","包羞。","有命无咎，疇離祉。","休否，大人吉。其亡其亡，繫于苞桑。","傾否，先否後喜。"]],
      13: ["同人","同人于野，亨。利涉大川，利君子貞。",["同人于門，无咎。","同人于宗，吝。","伏戎于莽，升其高陵，三歲不興。","乘其墉，弗克攻，吉。","同人，先號咷而後笑，大師克相遇。","同人于郊，无悔。"]],
      14: ["大有","大有，元亨。",["无交害，匪咎，艱則无咎。","大車以載，有攸往，无咎。","公用亨于天子，小人弗克。","匪其彭，无咎。","厥孚交如，威如，吉。","自天祐之，吉无不利。"]],
      15: ["謙","謙，亨，君子有終。",["謙謙君子，用涉大川，吉。","鳴謙，貞吉。","勞謙，君子有終，吉。","无不利，撝謙。","不富以其鄰，利用侵伐，无不利。","鳴謙，利用行師，征邑國。"]],
      16: ["豫","豫，利建侯、行師。",["鳴豫，凶。","介于石，不終日，貞吉。","盱豫，悔，遲有悔。","由豫，大有得。勿疑，朋盍簪。","貞疾，恒不死。","冥豫，成有渝，无咎。"]],
      17: ["隨","隨，元亨利貞，无咎。",["官有渝，貞吉。出門交有功。","係小子，失丈夫。","係丈夫，失小子。隨有求得，利居貞。","隨有獲，貞凶。有孚，在道以明，何咎？","孚于嘉，吉。","拘係之，乃從維之，王用亨于西山。"]],
      18: ["蠱","蠱，元亨，利涉大川。先甲三日，後甲三日。",["幹父之蠱。有子，考无咎，厲，終吉。","幹母之蠱，不可貞。","幹父之蠱，小有悔，无大咎。","裕父之蠱，往見吝。","幹父之蠱，用譽。","不事王侯，高尚其事。"]],
      19: ["臨","臨，元亨利貞，至于八月有凶。",["咸臨，貞吉。","咸臨，吉，无不利。","甘臨，无攸利，既憂之，无咎。","至臨，无咎。","知臨，大君之宜，吉。","敦臨，吉，无咎。"]],
      20: ["觀","觀，盥而不薦，有孚顒若。",["童觀，小人无咎，君子吝。","闚觀，利女貞。","觀我生，進退。","觀國之光，利用賓于王。","觀我生，君子无咎。","觀其生，君子无咎。"]],
      21: ["噬嗑","噬嗑，亨，利用獄。",["屨校滅趾，无咎。","噬膚，滅鼻，无咎。","噬腊肉，遇毒。小吝无咎。","噬乾胏，得金矢，利艱貞吉。","噬乾肉，得黃金，貞厲无咎。","何校滅耳，凶。"]],
      22: ["賁","賁，亨，小利有攸往。",["賁其趾，舍車而徒。","賁其須。","賁如濡如，永貞吉。","賁如皤如，白馬翰如，匪寇婚媾。","賁于丘園，束帛戔戔。吝，終吉。","白賁，无咎。"]],
      23: ["剝","剝，不利有攸往。",["剝床以足，蔑貞凶。","剝床以辨，蔑貞凶。","剝之无咎。","剝床以膚，凶。","貫魚以宮人寵，无不利。","碩果不食，君子得輿，小人剝廬。"]],
      24: ["復","復，亨。出入无疾，朋來无咎。反復其道，七日來復，利有攸往。",["不遠復，无祇悔，元吉。","休復，吉。","頻復，厲，无咎。","中行獨復。","敦復，无悔。","迷復，凶，有災眚，用行師，終有大敗。以其國君，凶。至于十年不克征。"]],
      25: ["无妄","无妄，元亨利貞。其匪正有眚，不利有攸往。",["无妄往，吉。","不耕穫，不菑畬，則利有攸往。","无妄之災，或繫之牛，行人之得，邑人之災。","可貞，无咎。","无妄之疾，勿藥有喜。","无妄行，有眚，无攸利。"]],
      26: ["大畜","大畜，利貞，不家食吉，利涉大川。",["有厲，利已。","輿說輹。","良馬逐，利艱貞。曰閑輿衛，利有攸往。","童牛之牿，元吉。","豶豕之牙，吉。","何天之衢，亨。"]],
      27: ["頤","頤，貞吉，觀頤，自求口實。",["舍爾靈龜，觀我朵頤，凶。","顛頤，拂經，于丘頤，征凶。","拂頤，貞凶。十年勿用，无攸利。","顛頤，吉，虎視眈眈，其欲逐逐，无咎。","拂經，居貞吉，不可涉大川。","由頤，厲吉，利涉大川。"]],
      28: ["大過","大過，棟橈。利有攸往，亨。",["藉用白茅，无咎。","枯楊生稊，老夫得其女妻，无不利。","棟橈，凶。","棟隆，吉，有它吝。","枯楊生華，老婦得其士夫，无咎无譽。","過涉滅頂，凶，无咎。"]],
      29: ["坎","習坎，有孚，維心亨，行有尚。",["習坎，入于坎窞，凶。","坎，有險，求小得。","來之坎坎，險且枕，入于坎窞，勿用。","樽酒，簋貳，用缶，納約自牖，終无咎。","坎不盈，祗既平，无咎。","係用黴纆，寘于叢棘，三歲不得，凶。"]],
      30: ["離","離，利貞，亨，畜牝牛，吉。",["履錯然，敬之，无咎。","黃離，元吉。","日昃之離，不鼓缶而歌，則大耋之嗟，凶。","突如其來如，焚如，死如，棄如。","出涕沱若，戚嗟若，吉。","王用出征，有嘉折首，獲匪其醜，无咎。"]],
      31: ["咸","咸，亨，利貞，取女吉。",["咸其拇。","咸其腓，凶，居吉。","咸其股，執其隨，往吝。","貞吉，悔亡，憧憧往來，朋從爾思。","咸其脢，无悔。","咸其輔頰舌。"]],
      32: ["恆","恒，亨，无咎，利貞，利有攸往。",["浚恒，貞凶，无攸利。","悔亡。","不恒其德，或承之羞，貞吝。","田无禽。","恒其德貞，婦人吉，夫子凶。","振恒，凶。"]],
      33: ["遯","遯，亨，小利貞。",["遯尾，厲。勿用有攸往。","執之用黃牛之革，莫之勝說。","係遯，有疾厲，畜臣妾吉。","好遯，君子吉，小人否。","嘉遯，貞吉。","肥遯，无不利。"]],
      34: ["大壯","大壯，利貞。",["壯于趾，征凶，有孚。","貞吉。","小人用壯，君子用罔。貞厲，羝羊觸藩，羸其角。","貞吉，悔亡，藩決不羸，壯于大輿之輹。","喪羊于易，无悔。","羝羊觸藩，不能退，不能遂，无攸利，艱則吉。"]],
      35: ["晉","晉，康侯用錫馬蕃庶，晝日三接。",["晉如摧如，貞吉。罔孚裕，无咎。","晉如愁如，貞吉。受茲介福，于其王母。","眾允，悔亡。","晉如鼫鼠，貞厲。","悔亡，失得勿恤。往吉无不利。","晉其角，維用伐邑。厲吉无咎，貞吝。"]],
      36: ["明夷","明夷，利艱貞。",["明夷于飛，垂其翼，君子于行，三日不食。有攸往，主人有言。","明夷，夷于左股，用拯馬壯吉。","明夷于南狩，得其大首，不可疾貞。","入于左腹，獲明夷之心，于出門庭。","箕子之明夷，利貞。","不明晦，初登于天，後入于地。"]],
      37: ["家人","家人，利女貞。",["閑有家，悔亡。","无攸遂，在中饋，貞吉。","家人嗃嗃，悔厲吉，婦子嘻嘻，終吝。","富家，大吉。","王假有家，勿恤，吉。","有孚，威如，終吉。"]],
      38: ["睽","睽，小事吉。",["悔亡，喪馬勿逐，自復。見惡人，无咎。","遇主于巷，无咎。","見輿曳，其牛掣，其人天且劓，无初有終。","睽孤，遇元夫。交孚，厲无咎。","悔亡。厥宗噬膚，往何咎。","睽孤，見豕負塗，載鬼一車，先張之弧，後說之弧，匪寇婚媾。往，遇雨則吉。"]],
      39: ["蹇","蹇，利西南，不利東北，利見大人，貞吉。",["往蹇來譽。","王臣蹇蹇，匪躬之故。","往蹇來反。","往蹇來連。","大蹇朋來。","往蹇來碩，吉，利見大人。"]],
      40: ["解","解，利西南，无所往，其來復吉；有攸往，夙吉。",["无咎。","田獲三狐，得黃矢，貞吉。","負且乘，致寇至，貞吝。","解而拇，朋至斯孚。","君子維有解，吉，有孚于小人。","公用射隼于高墉之上，獲之，无不利。"]],
      41: ["損","損，有孚，元吉，无咎可貞，利有攸往。曷之用，二簋可用享。",["已事遄往，无咎，酌損之。","利貞，征凶。弗損，益之。","三人行，則損一人，一人行，則得其友。","損其疾，使遄有喜，无咎。","或益之十朋之龜，弗克違，元吉。","弗損，益之，无咎，貞吉，利有攸往，得臣无家。"]],
      42: ["益","益，利有攸往，利涉大川。",["利用為大作，元吉，无咎。","或益之十朋之龜，弗克違，永貞吉。王用享于帝，吉。","益之用凶事，无咎。有孚中行，告公用圭。","中行，告公從，利用為依遷國。","有孚惠心，勿問元吉。有孚惠我德。","莫益之，或擊之，立心勿恒，凶。"]],
      43: ["夬","夬，揚于王庭，孚號有厲。告自邑，不利即戎，利有攸往。",["壯于前趾，往不勝為咎。","惕號，莫夜有戎，勿恤。","壯于頄，有凶。君子夬夬，獨行，遇雨若濡。有慍无咎。","臀无膚，其行次且，牽羊悔亡，聞言不信。","莧陸夬夬，中行无咎。","无號，終有凶。"]],
      44: ["姤","姤，女壯，勿用取女。",["繫于金柅，貞吉。有攸往，見凶。羸豕孚蹢躅。","包有魚，无咎，不利賓。","臀无膚，其行次且，厲，无大咎。","包无魚，起凶。","以杞包瓜，含章，有隕自天。","姤其角，吝，无咎。"]],
      45: ["萃","萃，亨，王假有廟，利見大人，亨，利貞。用大牲吉。利有攸往。",["有孚不終，乃亂乃萃，若號。一握為笑，勿恤，往无咎。","引吉，无咎，孚乃利用禴。","萃如嗟如，无攸利。往无咎，小吝。","大吉，无咎。","萃有位，无咎，匪孚。元永貞，悔亡。","齎咨涕洟，无咎。"]],
      46: ["升","升，元亨。用見大人，勿恤。南征吉。",["允升，大吉。","孚乃利用禴，无咎。","升虛邑。","王用亨于岐山，吉，无咎。","貞吉，升階。","冥升，利于不息之貞。"]],
      47: ["困","困，亨，貞大人吉，无咎。有言不信。",["臀困于株木，入于幽谷，三歲不覿。","困于酒食，朱紱方來，利用享祀，征凶，无咎。","困于石，據于蒺蔾，入于其宮，不見其妻，凶。","來徐徐，困于金車。吝，有終。","劓刖，困于赤紱，乃徐有說。利用祭祀。","困于葛藟，于臲卼，曰動悔有悔，征吉。"]],
      48: ["井","井，改邑不改井，无喪无得，往來井，井汔至，亦未繘井，羸其瓶，凶。",["井泥不食，舊井无禽。","井谷射鮒，甕敝漏。","井渫不食，為我心惻，可用汲。王明，並受其福。","井甃无咎。","井洌，寒泉食。","井收勿幕，有孚元吉。"]],
      49: ["革","革，已日乃孚，元亨利貞，悔亡。",["鞏用黃牛之革。","已日乃革之，征吉，无咎。","征凶，貞厲，革言三就，有孚。","悔亡，有孚，改命吉。","大人虎變，未占有孚。","君子豹變，小人革面，征凶，居貞吉。"]],
      50: ["鼎","鼎，元吉亨。",["鼎顛趾，利出否，得妾以其子，无咎。","鼎有實，我仇有疾，不我能即，吉。","鼎耳革，其行塞，雉膏不食。方雨虧悔，終吉。","鼎折足，覆公餗，其形渥，凶。","鼎黃耳金鉉，利貞。","鼎玉鉉，大吉，无不利。"]],
      51: ["震","震，亨。震來虩虩，笑言啞啞，震驚百里，不喪匕鬯。",["震來虩虩，後笑言啞啞，吉。","震來厲，億喪貝，躋于九陵。勿逐，七日得。","震蘇蘇，震行无眚。","震遂泥。","震往來厲，億无喪，有事。","震索索，視矍矍，征凶。震不于其躬于其鄰，无咎。婚媾有言。"]],
      52: ["艮","艮其背，不獲其身；行其庭，不見其人。无咎。",["艮其趾，无咎，利永貞。","艮其腓，不拯其隨，其心不快。","艮其限，列其夤，厲薰心。","艮其身，无咎。","艮其輔，言有序，悔亡。","敦艮，吉。"]],
      53: ["漸","漸，女歸吉，利貞。",["鴻漸于干，小子厲，有言，无咎。","鴻漸于磐，飲食衎衎，吉。","鴻漸于陸，夫征不復，婦孕不育，凶，利禦寇。","鴻漸于木，或得其桷，无咎。","鴻漸于陵，婦三歲不孕，終莫之勝，吉。","鴻漸于陸，其羽可用為儀，吉。"]],
      54: ["歸妹","歸妹，征凶，无攸利。",["歸妹以娣，跛能履，征吉。","眇能視，利幽人之貞。","歸妹以須，反歸以娣。","歸妹愆期，遲歸有時。","帝乙歸妹，其君之袂，不如其娣之袂良。月幾望，吉。","女承筐无實，士刲羊无血，无攸利。"]],
      55: ["豐","豐，亨，王假之，勿憂，宜日中。",["遇其配主，雖旬无咎，往有尚。","豐其蔀，日中見斗。往得疑疾，有孚發若，吉。","豐其沛，日中見沬。折其右肱，无咎。","豐其蔀，日中見斗，遇其夷主，吉。","來章，有慶譽，吉。","豐其屋，蔀其家，闚其戶，闃其无人，三歲不覿，凶。"]],
      56: ["旅","旅，小亨，旅貞吉。",["旅瑣瑣，斯其所取災。","旅即次，懷其資，得童僕貞。","旅焚其次，喪其童僕，貞厲。","旅于處，得其資斧，我心不快。","射雉，一矢亡，終以譽命。","鳥焚其巢，旅人先笑後號咷，喪牛于易，凶。"]],
      57: ["巽","巽，小亨，利有攸往，利見大人。",["進退，利武人之貞。","巽在床下，用史巫紛若，吉无咎。","頻巽，吝。","悔亡，田獲三品。","貞吉，悔亡，无不利。无初有終，先庚三日，後庚三日，吉。","巽在床下，喪其資斧，貞凶。"]],
      58: ["兌","兌，亨，利貞。",["和兌吉。","孚兌，吉，悔亡。","來兌，凶。","商兌未寧，介疾有喜。","孚于剝，有厲。","引兌。"]],
      59: ["渙","渙，亨，王假有廟，利涉大川，利貞。",["用拯馬壯，吉。","渙奔其机，悔亡。","渙其躬，无悔。","渙其群，元吉。渙有丘，匪夷所思。","渙汗其大號，渙王居，无咎。","渙其血，去逖出，无咎。"]],
      60: ["節","節，亨。苦節，不可貞。",["不出戶庭，无咎。","不出門庭，凶。","不節若，則嗟若，无咎。","安節，亨。","甘節，吉，往有尚。","苦節，貞凶，悔亡。"]],
      61: ["中孚","中孚，豚魚吉，利涉大川，利貞。",["虞吉，有它不燕。","鳴鶴在陰，其子和之；我有好爵，吾與爾靡之。","得敵，或鼓或罷，或泣或歌。","月幾望，馬匹亡，无咎。","有孚攣如，无咎。","翰音登于天，貞凶。"]],
      62: ["小過","小過，亨，利貞。可小事，不可大事。飛鳥遺之音，不宜上，宜下。大吉。",["飛鳥以凶。","過其祖，遇其妣，不及其君，遇其臣，无咎。","弗過防之，從或戕之，凶。","无咎，弗過遇之，往厲必戒，勿用永貞。","密雲不雨，自我西郊，公弋取彼在穴。","弗遇過之，飛鳥離之，凶，是謂災眚。"]],
      63: ["既濟","既濟，亨小，利貞。初吉終亂。",["曳其輪，濡其尾，无咎。","婦喪其茀，勿逐，七日得。","高宗伐鬼方，三年克之，小人勿用。","繻有衣袽，終日戒。","東鄰殺牛，不如西鄰之禴祭，實受其福。","濡其首，厲。"]],
      64: ["未濟","未濟，亨。小狐汔濟，濡其尾，无攸利。",["濡其尾，吝。","曳其輪，貞吉。","未濟，征凶，利涉大川。","貞吉，悔亡，震用伐鬼方，三年有賞于大國。","貞吉无悔，君子之光，有孚，吉。","有孚于飲酒，无咎。濡其首，有孚，失是。"]],
    };

    // 最低位为初爻：低三位是下卦，高三位是上卦。
    const HEXAGRAM_BITS = [
      -1,
      63, 0, 17, 34, 23, 58, 2, 16, 55, 59, 7, 56, 61, 47, 4, 8,
      25, 38, 3, 48, 41, 37, 32, 1, 57, 39, 33, 30, 18, 45, 28, 14,
      60, 15, 40, 5, 53, 43, 20, 10, 35, 49, 31, 62, 24, 6, 26, 22,
      29, 46, 9, 36, 52, 11, 13, 44, 54, 27, 50, 19, 51, 12, 21, 42
    ];

    const SIMPLE_NAMES = [
      "", "乾", "坤", "屯", "蒙", "需", "讼", "师", "比", "小畜", "履",
      "泰", "否", "同人", "大有", "谦", "豫", "随", "蛊", "临", "观",
      "噬嗑", "贲", "剥", "复", "无妄", "大畜", "颐", "大过", "坎", "离",
      "咸", "恒", "遁", "大壮", "晋", "明夷", "家人", "睽", "蹇", "解",
      "损", "益", "夬", "姤", "萃", "升", "困", "井", "革", "鼎",
      "震", "艮", "渐", "归妹", "丰", "旅", "巽", "兑", "涣", "节",
      "中孚", "小过", "既济", "未济"
    ];

    const TRIGRAM_NAMES = ["坤", "震", "坎", "兑", "艮", "离", "巽", "乾"];
    const TRIGRAM_IMAGES = ["地", "雷", "水", "泽", "山", "火", "风", "天"];
    const USE_NINE = "用九：見羣龍无首，吉。";
    const USE_SIX = "用六：利永貞。";

    const HEXAGRAMS_BY_BITS = new Map();
    const HEXAGRAMS_BY_NUMBER = new Map();

    function buildHexagramIndexes() {
      for (let number = 1; number <= 64; number += 1) {
        const text = HEXAGRAM_TEXTS[number];
        if (!text || !Array.isArray(text[2]) || text[2].length !== 6) {
          throw new Error(`第 ${number} 卦经文不完整`);
        }
        const gua = Object.freeze({
          bits: HEXAGRAM_BITS[number],
          number,
          name: SIMPLE_NAMES[number],
          classicalName: text[0],
          judgment: text[1],
          lines: Object.freeze([...text[2]])
        });
        HEXAGRAMS_BY_BITS.set(gua.bits, gua);
        HEXAGRAMS_BY_NUMBER.set(number, gua);
      }
      if (HEXAGRAMS_BY_BITS.size !== 64) throw new Error("六十四卦位图有重复");
    }

    function fourRemainder(stalks) {
      const remainder = stalks % 4;
      return remainder === 0 ? 4 : remainder;
    }

    function performChange(before, number, rng) {
      if (![1, 2, 3].includes(number)) throw new Error("一爻只包含三变");
      const desiredLeftRemainder = rng.int(4) + 1;
      const possibleLeft = [];
      for (let left = 1; left < before - 1; left += 1) {
        if (fourRemainder(left) === desiredLeftRemainder) possibleLeft.push(left);
      }
      const left = possibleLeft[rng.int(possibleLeft.length)];
      const rightBeforeHang = before - left;
      const rightAfterHang = rightBeforeHang - 1;
      const leftRemainder = fourRemainder(left);
      const rightRemainder = fourRemainder(rightAfterHang);
      const removed = 1 + leftRemainder + rightRemainder;
      const after = before - removed;
      const allowed = number === 1 ? [5, 9] : [4, 8];
      if (!allowed.includes(removed) || after % 4 !== 0) {
        throw new Error("揲蓍状态违反大衍筮法守恒关系");
      }
      return Object.freeze({
        number, before, left, rightBeforeHang, rightAfterHang,
        leftRemainder, rightRemainder, removed, after
      });
    }

    function castLine(rng) {
      let active = 49;
      const changes = [];
      for (let number = 1; number <= 3; number += 1) {
        const change = performChange(active, number, rng);
        changes.push(change);
        active = change.after;
      }
      const value = active / 4;
      if (![6, 7, 8, 9].includes(value)) throw new Error("未能得到合法爻值");
      return Object.freeze({ value, changes: Object.freeze(changes) });
    }

    function makeResult(lines, lineCasts = []) {
      if (!Array.isArray(lines) || lines.length !== 6 || lines.some(value => ![6, 7, 8, 9].includes(value))) {
        throw new Error("六爻必须由 6、7、8、9 组成");
      }
      let baseBits = 0;
      let changedBits = 0;
      const movingPositions = [];
      lines.forEach((value, index) => {
        let bit = value % 2;
        baseBits |= bit << index;
        if (value === 6 || value === 9) {
          movingPositions.push(index + 1);
          bit = 1 - bit;
        }
        changedBits |= bit << index;
      });
      return Object.freeze({
        lines: Object.freeze([...lines]),
        lineCasts: Object.freeze([...lineCasts]),
        baseBits,
        changedBits,
        movingPositions: Object.freeze(movingPositions),
        hasChanges: movingPositions.length > 0
      });
    }

    function castHexagram(rng = makeCryptoRng()) {
      const lineCasts = Array.from({ length: 6 }, () => castLine(rng));
      return makeResult(lineCasts.map(line => line.value), lineCasts);
    }

    function makeResultFromBits(baseBits, changedBits) {
      getHexagram(baseBits);
      getHexagram(changedBits);
      return makeResult(Array.from({ length: 6 }, (_, index) => {
        const base = (baseBits >> index) & 1;
        const changed = (changedBits >> index) & 1;
        return base === changed ? (base ? 7 : 8) : (base ? 9 : 6);
      }));
    }

    function changeHexagramLine(result, kind, position) {
      if (!["base", "changed"].includes(kind) || !Number.isInteger(position) || position < 1 || position > 6) {
        throw new Error("请选择本卦或之卦的六个爻位之一。");
      }
      const mask = 1 << (position - 1);
      const baseBits = result.baseBits ^ (kind === "base" ? mask : 0);
      const changedBits = result.changedBits ^ (kind === "changed" ? mask : 0);
      return makeResultFromBits(baseBits, changedBits);
    }

    function parseManual(text) {
      let value = String(text).normalize("NFKC").trim();
      let expectedNumbers = null;
      if (/^https?:\/\//i.test(value)) {
        const url = new URL(value);
        const path = url.pathname.match(/^\/gua(\d+)-(\d+)\.html$/);
        if (!/^(www\.)?zhouyipro\.com$/i.test(url.hostname) || !path) {
          throw new Error("请粘贴周易 Pro 的本卦之卦链接，或输入六位爻值。");
        }
        expectedNumbers = path.slice(1).map(Number);
        value = decodeURIComponent(url.hash.slice(1));
        if (!value) {
          const guas = expectedNumbers.map(number => HEXAGRAMS_BY_NUMBER.get(number));
          if (guas.some(gua => !gua)) throw new Error("链接中的卦序应在 1 到 64 之间。");
          value = guas.map(gua => Array.from({ length: 6 }, (_, i) => (gua.bits >> i) & 1 ? 7 : 8).join("")).join("_");
        }
      }
      value = value.replace(/^#/, "").replace(/\s/g, "");
      const pair = value.match(/^([78]{6})_([78]{6})$/);
      let result;
      if (pair) {
        result = makeResult([...pair[1]].map((digit, i) => digit === pair[2][i] ? Number(digit) : digit === "7" ? 9 : 6));
      } else if (/^[6789]{6}$/.test(value)) {
        result = makeResult([...value].map(Number));
      } else {
        throw new Error("请输入六位 6/7/8/9（初爻→上爻），或本卦_之卦编码，如 778787_788788。");
      }
      if (expectedNumbers && (getHexagram(result.baseBits).number !== expectedNumbers[0] || getHexagram(result.changedBits).number !== expectedNumbers[1])) {
        throw new Error("链接中的卦名编号与六爻编码不一致，请核对链接。");
      }
      return result;
    }

    function fullName(gua) {
      const lower = gua.bits & 7;
      const upper = gua.bits >> 3;
      return lower === upper ? `${gua.name}为${TRIGRAM_IMAGES[upper]}` : `${TRIGRAM_IMAGES[upper]}${TRIGRAM_IMAGES[lower]}${gua.name}`;
    }

    function searchHexagrams(query) {
      const text = String(query).normalize("NFKC").replace(/\s/g, "");
      const guas = [...HEXAGRAMS_BY_NUMBER.values()];
      if (!text) return guas;
      if (/^\d+$/.test(text)) return guas.filter(gua => gua.number === Number(text));
      return guas.filter(gua => {
        const lower = gua.bits & 7, upper = gua.bits >> 3;
        const images = ["地", "雷", "水", "澤", "山", "火", "風", "天"];
        const traditional = lower === upper ? `${gua.classicalName}為${images[upper]}` : `${images[upper]}${images[lower]}${gua.classicalName}`;
        return [gua.name, gua.classicalName, fullName(gua), traditional].some(name => name.includes(text));
      });
    }

    function createResultHistory(limit = 50) {
      if (!Number.isInteger(limit) || limit < 1) throw new Error("历史步数必须是正整数");
      let current = null;
      const past = [], future = [];
      return Object.freeze({
        get current() { return current; },
        get canUndo() { return past.length > 0; },
        get canRedo() { return future.length > 0; },
        commit(result) {
          if (current && current.lines.join("") === result.lines.join("") && JSON.stringify(current.lineCasts) === JSON.stringify(result.lineCasts)) return false;
          if (current) past.push(current);
          if (past.length > limit) past.shift();
          current = result;
          future.length = 0;
          return true;
        },
        undo() {
          if (!past.length) return null;
          future.push(current);
          return current = past.pop();
        },
        redo() {
          if (!future.length) return null;
          past.push(current);
          return current = future.pop();
        }
      });
    }

    function relatedHexagrams(bits) {
      getHexagram(bits);
      const reversed = Array.from({ length: 6 }, (_, i) => ((bits >> i) & 1) << (5 - i)).reduce((a, b) => a | b, 0);
      return [
        { name: "互卦", description: "二三四爻作下卦，三四五爻作上卦。", gua: getHexagram(((bits >> 1) & 7) | (((bits >> 2) & 7) << 3)) },
        { name: "错卦", description: "六个爻位的阴阳全部反转。", gua: getHexagram(bits ^ 63) },
        { name: "综卦", description: "将六爻的上下顺序倒置。", gua: getHexagram(reversed) }
      ];
    }

    function cryptoInt(max) {
      if (!Number.isInteger(max) || max <= 0) throw new Error("随机上限必须是正整数");
      const range = 0x100000000;
      const limit = Math.floor(range / max) * max;
      const data = new Uint32Array(1);
      do { crypto.getRandomValues(data); } while (data[0] >= limit);
      return data[0] % max;
    }

    function makeCryptoRng() {
      return Object.freeze({ int: cryptoInt });
    }

    function seedHash(text) {
      let hash = 2166136261;
      for (const char of String(text)) {
        hash ^= char.codePointAt(0);
        hash = Math.imul(hash, 16777619);
      }
      return hash >>> 0;
    }

    function makeSeededRng(seed) {
      let state = seedHash(seed) || 0x6d2b79f5;
      return Object.freeze({
        int(max) {
          state += 0x6d2b79f5;
          let value = state;
          value = Math.imul(value ^ (value >>> 15), value | 1);
          value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
          value = ((value ^ (value >>> 14)) >>> 0) / 0x100000000;
          return Math.floor(value * max);
        }
      });
    }

    function getHexagram(bits) {
      const gua = HEXAGRAMS_BY_BITS.get(bits);
      if (!gua) throw new Error("卦象位图必须在 0 到 63 之间");
      return gua;
    }

    function lineLabel(bits, position) {
      if (position < 1 || position > 6) throw new Error("爻位必须在 1 到 6 之间");
      const polarity = ((bits >> (position - 1)) & 1) ? "九" : "六";
      if (position === 1) return `初${polarity}`;
      if (position === 6) return `上${polarity}`;
      return `${polarity}${"一二三四五六"[position - 1]}`;
    }

    function lineItem(role, gua, position) {
      return Object.freeze({
        role, gua, position,
        source: `${lineLabel(gua.bits, position)}爻辞`,
        text: gua.lines[position - 1]
      });
    }

    function judgmentItem(role, gua) {
      return Object.freeze({ role, gua, position: null, source: "卦辞", text: gua.judgment });
    }

    function interpret(result) {
      const base = getHexagram(result.baseBits);
      const changed = getHexagram(result.changedBits);
      const moving = result.movingPositions;
      const count = moving.length;
      let rule;
      let items;
      let notes = [];

      if (count === 0) {
        rule = "六爻皆不变，占本卦卦辞；以内卦为贞、外卦为悔。";
        items = [judgmentItem("主断", base)];
        notes = [
          `贞（内卦）：${TRIGRAM_NAMES[result.baseBits & 7]}`,
          `悔（外卦）：${TRIGRAM_NAMES[(result.baseBits >> 3) & 7]}`
        ];
      } else if (count === 1) {
        rule = "一爻变，占本卦变爻爻辞。";
        items = [lineItem("主断", base, moving[0])];
      } else if (count === 2) {
        rule = "二爻变，占本卦两个变爻爻辞，以上爻为主。";
        items = [lineItem("主断", base, moving[1]), lineItem("参看", base, moving[0])];
      } else if (count === 3) {
        rule = "三爻变，占本卦与之卦卦辞；本卦为贞、之卦为悔。";
        if (moving.includes(1)) {
          items = [judgmentItem("主断", changed), judgmentItem("参看", base)];
          notes = ["初爻变，属后十卦，以之卦（悔）为主。"];
        } else {
          items = [judgmentItem("主断", base), judgmentItem("参看", changed)];
          notes = ["初爻不变，属前十卦，以本卦（贞）为主。"];
        }
      } else if (count === 4) {
        const still = [1, 2, 3, 4, 5, 6].filter(position => !moving.includes(position));
        rule = "四爻变，占之卦两个不变爻爻辞，以下爻为主。";
        items = [lineItem("主断", changed, still[0]), lineItem("参看", changed, still[1])];
      } else if (count === 5) {
        const still = [1, 2, 3, 4, 5, 6].find(position => !moving.includes(position));
        rule = "五爻变，占之卦唯一不变爻爻辞。";
        items = [lineItem("主断", changed, still)];
      } else if (result.baseBits === 63) {
        rule = "六爻皆变，乾卦占用九。";
        items = [{ role: "主断", gua: base, position: null, source: "用九", text: USE_NINE }];
      } else if (result.baseBits === 0) {
        rule = "六爻皆变，坤卦占用六。";
        items = [{ role: "主断", gua: base, position: null, source: "用六", text: USE_SIX }];
      } else {
        rule = "六爻皆变，乾坤之外占之卦卦辞。";
        items = [judgmentItem("主断", changed)];
      }
      return Object.freeze({ changeCount: count, rule, items: Object.freeze(items), notes: Object.freeze(notes) });
    }

    function escapeHtml(value) {
      return String(value).replace(/[&<>"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]);
    }

    function renderMiniHex(bits) {
      return `<span class="mini-hex" aria-hidden="true">${[5, 4, 3, 2, 1, 0].map(i => `<span class="mini-line ${(bits >> i) & 1 ? "" : "yin"}"></span>`).join("")}</span>`;
    }

    function writeResultHash(result, location = window.location, history = window.history) {
      const hash = "#" + result.lines.join("");
      if (location.hash === hash) return;
      try { history.replaceState(history.state, "", hash); }
      catch { location.hash = hash; }
    }

    function renderHexCard(gua, result, kind, standalone = false) {
      const isBase = kind === "base";
      const rows = [];
      for (let position = 6; position >= 1; position -= 1) {
        const bit = (gua.bits >> (position - 1)) & 1;
        const value = result.lines[position - 1];
        const moving = value === 6 || value === 9;
        const label = lineLabel(gua.bits, position);
        const attributes = `type="button" data-kind="${kind}" data-position="${position}" aria-pressed="${Boolean(bit)}" aria-label="${isBase ? "本卦" : "之卦"}${label}，${bit ? "阳爻，点击改为阴爻" : "阴爻，点击改为阳爻"}"`;
        rows.push(`<button class="yao-row ${!standalone && isBase && moving ? "moving" : ""}" style="top:${(6 - position) * 100 / 6}%" ${attributes}>
          <span class="yao-label">${label}</span>
          <svg class="yao-glyph" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true" focusable="false">${bit ? '<rect x="0" y="21" width="100" height="58"/>' : '<rect x="0" y="21" width="46" height="58"/><rect x="54" y="21" width="46" height="58"/>'}</svg>
          <span class="yao-value">${isBase ? `${value}${value === 9 ? "○" : value === 6 ? "×" : ""}` : ""}</span>
          <span class="yao-tooltip" aria-hidden="true">${label}：${escapeHtml(gua.lines[position - 1])}</span>
        </button>`);
      }
      return `<article class="hex-card ${isBase ? "" : "changed"}">
        <div class="hex-kicker"><span>${isBase ? "本卦" : "之卦"}</span></div>
        <div class="yao-stack">${rows.join("")}</div>
        <div class="hex-caption"><h3 class="hex-name"><span class="hex-number">${gua.number}</span><button type="button" class="hex-picker-trigger" data-picker-kind="${kind}" aria-label="选择${isBase ? "本卦" : "之卦"}，当前${gua.name}" title="选卦">${gua.name}</button></h3></div>
      </article>`;
    }

    function renderScripture(gua, reading, kind, standalone = false) {
      const chosen = standalone ? [] : reading.items.filter(item => item.gua.number === gua.number);
      const scope = kind === "本卦" ? "base" : "changed";
      const passage = (label, text, item, row) => {
        const position = row >= 3 && row <= 8 ? 9 - row : null;
        const attributes = position ? `data-kind="${scope}" data-position="${position}"` : "";
        const heading = position ? `<button class="line-link" type="button" data-locate-kind="${scope}" data-position="${position}" aria-label="定位${kind}${label}卦画">${label}</button>` : label;
        return `<p class="scripture-line ${row === 2 ? "judgment-passage" : ""} ${item ? "selected" : ""} ${item?.role === "参看" ? "secondary" : ""}" style="grid-row:${row}" ${attributes}><strong>${heading}${item ? `<span class="focus-label">${item.role === "主断" ? "主解" : "辅解"}</span>` : ""}</strong>${escapeHtml(text)}</p>`;
      };
      const judgment = passage("卦辞", gua.judgment, chosen.find(item => item.source === "卦辞"), 2);
      const lines = [6, 5, 4, 3, 2, 1].map((position, index) => passage(lineLabel(gua.bits, position), gua.lines[position - 1], chosen.find(item => item.position === position), index + 3)).join("");
      const special = gua.number === 1 ? passage("用九", USE_NINE.replace(/^用九：/, ""), chosen.find(item => item.source === "用九"), 9)
        : gua.number === 2 ? passage("用六", USE_SIX.replace(/^用六：/, ""), chosen.find(item => item.source === "用六"), 9) : "";
      return `<article>${standalone ? "" : `<h3 class="scripture-heading">${kind} · ${gua.name}</h3>`}${judgment}${lines}${special}</article>`;
    }

    let currentResult = null;
    let currentView = 2;
    const resultHistory = createResultHistory();
    let pickerContext = null;
    let hoveredLine = null;
    let focusedLine = null;

    function renderReadingPassages(reading) {
      return reading.items.map(item => {
        const source = item.position ? lineLabel(item.gua.bits, item.position) : item.source;
        const text = item.source === "用九" || item.source === "用六" ? item.text.replace(/^用[九六]：/, "") : item.text;
        return `<p class="rule-passage"><strong>${item.gua.name} · ${source}（${item.role === "主断" ? "主解" : "辅解"}）</strong><br>${escapeHtml(text)}</p>`;
      }).join("");
    }

    function renderRelations(gua) {
      return `<h3>${gua.name}的卦象关系</h3><div class="relation-grid">${relatedHexagrams(gua.bits).map(item => `
        <article class="relation-card"><span>${item.name} · 第 ${item.gua.number} 卦</span>
          <h4>${item.gua.name}</h4><p class="definition">${item.description}</p>
          <p>${escapeHtml(item.gua.judgment)}</p></article>`).join("")}</div>`;
    }

    function renderTrace(result) {
      if (!result.lineCasts.length) return "<p>当前为六爻复盘。自动起卦会在这里记录六爻十八变的揲蓍过程。</p>";
      return result.lineCasts.map((line, index) => {
        const changes = line.changes.map(change => `
          <div class="trace-change">第${change.number}变：${change.before}策；分二左${change.left}/右${change.rightBeforeHang}；右挂一后${change.rightAfterHang}；归奇左${change.leftRemainder}/右${change.rightRemainder}；共去${change.removed}，存${change.after}。</div>
        `).join("");
        return `<div class="trace-line">${escapeHtml(lineLabel(result.baseBits, index + 1))} · 得 ${line.value}</div>${changes}`;
      }).join("");
    }

    function renderReadingView(result) {
      hoveredLine = null;
      focusedLine = null;
      const standalone = currentView === 1;
      const base = getHexagram(result.baseBits);
      const changed = getHexagram(result.changedBits);
      const reading = standalone ? { items: [], notes: [], rule: "" } : interpret(result);
      document.getElementById("readingHeading").textContent = standalone ? `${base.name}卦经文` : "经文与取辞";
      document.querySelector("#readingPanel .rule-line").hidden = standalone;
      document.getElementById("readingNotes").hidden = standalone;
      document.getElementById("resultTitle").textContent = standalone ? base.name : `${base.name}之${changed.name}`;
      document.getElementById("baseSymbol").innerHTML = renderMiniHex(base.bits);
      document.getElementById("changedSymbol").innerHTML = renderMiniHex(changed.bits);
      document.getElementById("resultSummary").textContent = `${standalone ? base.name : `${base.name} → ${changed.name}`}　·　${result.lines.join("")}（初爻→上爻）`;
      document.getElementById("hexagramGrid").innerHTML = renderHexCard(base, result, "base", standalone) + (standalone ? "" : renderHexCard(changed, result, "changed"));
      document.getElementById("readingRule").textContent = reading.rule;
      document.getElementById("readingPassages").innerHTML = renderReadingPassages(reading);
      document.getElementById("readingNotes").innerHTML = reading.notes.map(note => `<p class="reading-note">${escapeHtml(note)}</p>`).join("");
      document.getElementById("scriptureContent").innerHTML = renderScripture(base, reading, "本卦", standalone) + (!standalone && result.hasChanges ? renderScripture(changed, reading, "之卦") : "");
      document.getElementById("scriptureContent").classList.toggle("single", standalone || !result.hasChanges);
      document.getElementById("relationsContent").innerHTML = renderRelations(base) + (!standalone && result.hasChanges ? renderRelations(changed) : "");
    }

    function renderResult(result, { navigate = true, updateHash = true, recordHistory = true } = {}) {
      if (recordHistory) resultHistory.commit(result);
      currentResult = result;
      renderReadingView(result);
      document.getElementById("manualInput").value = result.lines.join("");
      document.getElementById("relationsDetails").open = false;
      document.getElementById("traceContent").innerHTML = renderTrace(result);
      document.getElementById("tracePanel").open = false;
      document.getElementById("emptyState").hidden = true;
      document.getElementById("resultSection").hidden = false;
      document.getElementById("tracePanel").hidden = false;
      document.getElementById("relationsDetails").hidden = false;
      if (updateHash) writeResultHash(result);
      if (navigate) {
        document.getElementById("tracePanel").open = Boolean(result.lineCasts.length && document.getElementById("verboseInput").checked);
        document.getElementById("settingsDetails").open = false;
      }
      updateHistoryControls();
    }

    function updateHistoryControls() {
      document.getElementById("historyActions").hidden = !resultHistory.canUndo && !resultHistory.canRedo;
      document.getElementById("undoButton").disabled = !resultHistory.canUndo;
      document.getElementById("redoButton").disabled = !resultHistory.canRedo;
    }

    function moveThroughHistory(direction) {
      const result = direction === "undo" ? resultHistory.undo() : resultHistory.redo();
      if (!result) return false;
      clearError();
      renderResult(result, { navigate: false, recordHistory: false });
      document.getElementById("historyStatus").textContent = `${direction === "undo" ? "已撤销" : "已重做"}，${getHexagram(result.baseBits).name}卦`;
      return true;
    }

    function renderPickerOptions() {
      const guas = searchHexagrams(document.getElementById("pickerSearch").value);
      const selected = currentResult ? getHexagram(pickerContext.kind === "base" ? currentResult.baseBits : currentResult.changedBits).number : null;
      document.getElementById("pickerGrid").innerHTML = guas.map(gua => {
        return `<button class="picker-option" type="button" data-number="${gua.number}" aria-label="第${gua.number}卦 ${gua.name}" aria-pressed="${selected === gua.number}" title="${fullName(gua)}">${renderMiniHex(gua.bits)}<span>${gua.name}</span><span class="picker-number">${gua.number}</span></button>`;
      }).join("");
      document.getElementById("pickerEmpty").hidden = guas.length > 0;
    }

    function openHexagramPicker(kind, opener) {
      pickerContext = { kind, opener };
      document.getElementById("pickerTitle").textContent = currentResult ? `选择${kind === "base" ? "本卦" : "之卦"}` : "选卦";
      document.getElementById("pickerSearch").value = "";
      renderPickerOptions();
      document.getElementById("hexagramPicker").showModal();
      document.getElementById("pickerSearch").focus();
    }

    function chooseHexagram(number) {
      const gua = HEXAGRAMS_BY_NUMBER.get(number);
      if (!gua || !pickerContext) return;
      const kind = pickerContext.kind;
      const oldBits = currentResult ? (kind === "base" ? currentResult.baseBits : currentResult.changedBits) : null;
      if (oldBits !== gua.bits) {
        const base = !currentResult || kind === "base" ? gua.bits : currentResult.baseBits;
        const changed = !currentResult || kind === "changed" ? gua.bits : currentResult.changedBits;
        clearError();
        renderResult(makeResultFromBits(base, changed), { navigate: false });
      }
      document.getElementById("hexagramPicker").close();
    }

    function syncLineInspection() {
      document.querySelectorAll(".is-inspected").forEach(el => el.classList.remove("is-inspected"));
      const active = hoveredLine || focusedLine;
      if (!active || !currentResult || (currentView === 1 && active.kind === "changed")) return;
      document.querySelector(`#hexagramGrid button[data-kind="${active.kind}"][data-position="${active.position}"]`)?.classList.add("is-inspected");
      const scriptureKind = currentResult.hasChanges ? active.kind : "base";
      document.querySelector(`#scriptureContent .scripture-line[data-kind="${scriptureKind}"][data-position="${active.position}"]`)?.classList.add("is-inspected");
    }

    function lineFromElement(element) {
      const button = element instanceof Element ? element.closest(".yao-row[data-position]") : null;
      return button ? { kind: button.dataset.kind, position: Number(button.dataset.position) } : null;
    }

    function showError(message) {
      const box = document.getElementById("errorBox");
      box.textContent = message;
      box.hidden = false;
    }

    function clearError() {
      document.getElementById("errorBox").hidden = true;
    }

    function initializeUi() {
      document.getElementById("emptySymbol").innerHTML = renderMiniHex(63);
      const picker = document.getElementById("hexagramPicker");
      document.getElementById("undoButton").addEventListener("click", () => moveThroughHistory("undo"));
      document.getElementById("redoButton").addEventListener("click", () => moveThroughHistory("redo"));
      document.getElementById("emptyPickerButton").addEventListener("click", event => openHexagramPicker("base", event.currentTarget));
      document.getElementById("closePickerButton").addEventListener("click", () => picker.close());
      picker.addEventListener("close", () => {
        if (!pickerContext) return;
        const trigger = currentResult ? document.querySelector(`[data-picker-kind="${pickerContext.kind}"]`) : pickerContext.opener;
        (trigger || document.getElementById("manualInput")).focus({ preventScroll: true });
        pickerContext = null;
      });
      picker.addEventListener("click", event => {
        if (event.target !== picker) return;
        const rect = picker.getBoundingClientRect();
        if (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) picker.close();
      });
      document.getElementById("pickerSearch").addEventListener("input", renderPickerOptions);
      document.getElementById("pickerSearch").addEventListener("keydown", event => {
        if (event.isComposing) return;
        const first = document.querySelector("#pickerGrid button");
        if (!first) return;
        if (event.key === "ArrowDown") { event.preventDefault(); first.focus(); }
        if (event.key === "Enter") { event.preventDefault(); chooseHexagram(Number(first.dataset.number)); }
      });
      document.getElementById("pickerGrid").addEventListener("click", event => {
        const option = event.target.closest("button[data-number]");
        if (option) chooseHexagram(Number(option.dataset.number));
      });
      document.getElementById("pickerGrid").addEventListener("keydown", event => {
        const options = [...document.querySelectorAll("#pickerGrid button")];
        const index = options.indexOf(event.target);
        if (index < 0) return;
        const columns = getComputedStyle(document.getElementById("pickerGrid")).gridTemplateColumns.split(" ").length;
        let next;
        if (event.key === "ArrowRight") next = index + 1;
        if (event.key === "ArrowLeft") next = index - 1;
        if (event.key === "ArrowDown") next = index + columns;
        if (event.key === "ArrowUp") next = index - columns;
        if (event.key === "Home") next = 0;
        if (event.key === "End") next = options.length - 1;
        if (next !== undefined) {
          event.preventDefault();
          const target = options[Math.max(0, Math.min(options.length - 1, next))];
          target.focus();
          target.scrollIntoView({ block: "nearest" });
        }
      });
      const viewStorageKey = "zhouyi.hexagramView.v1";
      const setHexagramView = (count, save = true) => {
        currentView = count;
        document.body.classList.toggle("single-hexagram", count === 1);
        document.getElementById("singleHexagramButton").setAttribute("aria-pressed", String(count === 1));
        document.getElementById("twoHexagramsButton").setAttribute("aria-pressed", String(count === 2));
        if (currentResult) renderReadingView(currentResult);
        if (save) {
          try { window.localStorage.setItem(viewStorageKey, String(count)); } catch {}
        }
      };
      let initialView = 2;
      try { initialView = window.localStorage.getItem(viewStorageKey) === "1" ? 1 : 2; } catch {}
      setHexagramView(initialView, false);
      document.getElementById("singleHexagramButton").addEventListener("click", () => setHexagramView(1));
      document.getElementById("twoHexagramsButton").addEventListener("click", () => setHexagramView(2));
      const displayOptions = {
        showHexKind: "show-hex-kind",
        showLineLabels: "show-line-labels",
        showLineValues: "show-line-values",
        showHexNumbers: "show-hex-numbers"
      };
      const displayStorageKey = "zhouyi.display.v1";
      let savedDisplay = {};
      try { savedDisplay = JSON.parse(window.localStorage.getItem(displayStorageKey)) || {}; } catch {}
      for (const [id, className] of Object.entries(displayOptions)) {
        const input = document.getElementById(id);
        input.checked = savedDisplay[id] === true;
        document.body.classList.toggle(className, input.checked);
        input.addEventListener("change", () => {
          document.body.classList.toggle(className, input.checked);
          const preferences = Object.fromEntries(Object.keys(displayOptions).map(key => [key, document.getElementById(key).checked]));
          try { window.localStorage.setItem(displayStorageKey, JSON.stringify(preferences)); } catch {}
        });
      }
      document.getElementById("castButton").addEventListener("click", () => {
        clearError();
        try {
          const seed = document.getElementById("seedInput").value.trim();
          renderResult(castHexagram(seed ? makeSeededRng(seed) : makeCryptoRng()));
        } catch (error) {
          showError(error.message || String(error));
        }
      });

      const loadManual = () => {
        clearError();
        try {
          renderResult(parseManual(document.getElementById("manualInput").value));
        } catch (error) {
          showError(error.message || String(error));
        }
      };
      document.getElementById("manualButton").addEventListener("click", loadManual);
      document.getElementById("manualInput").addEventListener("keydown", event => {
        if (event.key === "Enter" && !event.isComposing) loadManual();
      });
      document.getElementById("seedInput").addEventListener("keydown", event => {
        if (event.key === "Enter" && !event.isComposing) document.getElementById("castButton").click();
      });
      document.getElementById("exampleButton").addEventListener("click", () => {
        document.getElementById("manualInput").value = "778787_788788";
        loadManual();
      });
      document.getElementById("hexagramGrid").addEventListener("click", event => {
        const pickerButton = event.target.closest("button[data-picker-kind]");
        if (pickerButton) { openHexagramPicker(pickerButton.dataset.pickerKind, pickerButton); return; }
        const button = event.target.closest("button[data-position]");
        if (!button || !currentResult) return;
        const position = Number(button.dataset.position);
        const kind = button.dataset.kind;
        clearError();
        renderResult(changeHexagramLine(currentResult, kind, position), { navigate: false });
        document.querySelector(`button[data-kind="${kind}"][data-position="${position}"]`).focus({ preventScroll: true });
      });
      const diagram = document.getElementById("hexagramGrid");
      diagram.addEventListener("pointerover", event => {
        if (event.pointerType === "touch") return;
        hoveredLine = lineFromElement(event.target);
        syncLineInspection();
      });
      diagram.addEventListener("pointerout", event => {
        if (event.pointerType === "touch") return;
        hoveredLine = lineFromElement(event.relatedTarget);
        syncLineInspection();
      });
      diagram.addEventListener("focusin", event => {
        focusedLine = lineFromElement(event.target);
        syncLineInspection();
      });
      diagram.addEventListener("focusout", event => {
        focusedLine = lineFromElement(event.relatedTarget);
        syncLineInspection();
      });
      document.getElementById("scriptureContent").addEventListener("click", event => {
        const link = event.target.closest("button[data-locate-kind]");
        if (!link) return;
        const target = document.querySelector(`#hexagramGrid button[data-kind="${link.dataset.locateKind}"][data-position="${link.dataset.position}"]`);
        if (!target) return;
        hoveredLine = null;
        target.focus({ preventScroll: true });
        target.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "nearest" });
      });
      document.addEventListener("keydown", event => {
        if (picker.open || event.isComposing) return;
        const editing = event.target instanceof HTMLElement && (event.target.isContentEditable || event.target.closest("input, textarea, select"));
        if (!editing && (event.ctrlKey || event.metaKey) && !event.altKey) {
          const key = event.key.toLowerCase();
          const direction = key === "z" ? (event.shiftKey ? "redo" : "undo") : key === "y" && !event.shiftKey ? "redo" : null;
          if (direction && moveThroughHistory(direction)) event.preventDefault();
        }
        if (event.key === "Escape") {
          const settings = document.getElementById("settingsDetails");
          if (settings.open) { settings.open = false; settings.querySelector("summary").focus(); }
        }
      });
      const restoreHash = () => {
        clearError();
        try {
          const defaultGua = HEXAGRAMS_BY_NUMBER.get(15);
          const result = window.location.hash
            ? parseManual(decodeURIComponent(window.location.hash))
            : makeResultFromBits(defaultGua.bits, defaultGua.bits);
          if (currentResult && result.lines.join("") === currentResult.lines.join("")) return;
          renderResult(result, { navigate: false, updateHash: false });
        }
        catch (error) { showError(error.message || String(error)); }
      };
      window.addEventListener("hashchange", restoreHash, { signal: controller.signal });
      restoreHash();
    }

    buildHexagramIndexes();
    
    initializeUi();
  
  return () => controller.abort();
}
