import fs from "node:fs/promises";
import { fileURLToPath } from "node:url";
import postcss from "postcss";

// The downloadable offline edition is also the source for the blog edition.
const project = new URL("../", import.meta.url);
const source = await fs.readFile(new URL("public/downloads/zhouyi.html", project), "utf8");
const css = postcss.parse(source.match(/<style>([\s\S]*?)<\/style>/)[1]);
const markup = source.match(/<body>([\s\S]*?)<script>/)[1]
  .replace(/<(\/?)main>/g, "<$1div>").replace(/ autofocus/g, "").trim();
let engine = source.match(/<script>([\s\S]*?)<\/script>/)[1];

const scope = ".zhouyi-workbench";
css.walkRules((rule) => {
  rule.selectors = rule.selectors.map((selector) => {
    const scoped = selector.replace(/:root|\bbody\b|\.single-hexagram/g, (part) =>
      part === ".single-hexagram" ? `${scope}.single-hexagram` : scope);
    return scoped.includes(scope) ? scoped : `${scope} ${scoped}`;
  });
});
const colors = {
  "#343437": "var(--foreground)", "#79797e": "var(--muted)",
  "#e7e4e2": "var(--border)", "#b65349": "#B65349",
  "#fbefec": "color-mix(in srgb, #B65349 10%, var(--background))", "#f7f7f6": "var(--surface-2)",
  "#fff": "var(--surface)", "#bf8981": "#bf8981",
  "#9798a0": "var(--muted)", "#a8544e": "#a8544e",
  "#f4e2de": "var(--red-soft)", "#a3443e": "var(--foreground)",
  "#ab514a": "#ab514a", "#b47a74": "#b47a74",
  "#c16b62": "#c16b62", "#cf8279": "#cf8279",
  "#30282c0d": "var(--shadow-tint)", "#bc9992": "var(--border-strong)",
  "#29232942": "rgb(0 0 0 / .4)", "#c8948d": "#c8948d",
  "#a19395": "var(--muted)", "#74757e": "var(--muted)",
  "#e4e2e4": "var(--border)", "#84858d": "var(--muted)",
  "#a8564f": "#a8564f", "#fdf8f6": "color-mix(in srgb, #B65349 4%, var(--background))",
  "#ddb3aa": "#ddb3aa", "#a16159": "#a16159",
  "#f0ded8": "var(--red-soft)", "#a0a0a7": "var(--muted)",
  "#747680": "var(--muted)", "#f0eef0": "var(--border)",
  "#73747d": "var(--muted)", "#92939b": "var(--muted)",
  "#daa19a": "var(--border-strong)",
};
css.walkDecls((decl) => {
  if (decl.prop === "color-scheme" || decl.prop === "--muted") { decl.remove(); return; }
  if (decl.prop === "--surface") decl.prop = "--zhouyi-surface";
  decl.value = decl.value.replace(/var\(--surface\)/g, "var(--zhouyi-surface)")
    .replace(/#[\da-f]+\b/gi, (value) => colors[value.toLowerCase()] || value);
  if (decl.prop === "--font") decl.value = "var(--font-serif)";
  if (decl.prop === "--radius") decl.value = "var(--radius-card)";
});

engine = engine.replace(/globalThis\.ZhouyiCore = Object\.freeze\([\s\S]*?\n    \}\);/, "")
  .replace('history.replaceState(null, "", hash)', 'history.replaceState(history.state, "", hash)')
  .replace('window.addEventListener("hashchange", restoreHash);',
    'window.addEventListener("hashchange", restoreHash, { signal: controller.signal });')
  .replace('if (typeof document !== "undefined") initializeUi();', "initializeUi();");

const engineModule = `// Generated by npm run sync:zhouyi from public/downloads/zhouyi.html.
export function initializeZhouyi(root) {
  const controller = new AbortController();
  const document = {
    body: root,
    getElementById: (id) => root.querySelector(\x60#\x24{id}\x60),
    querySelector: (selector) => root.querySelector(selector),
    querySelectorAll: (selector) => root.querySelectorAll(selector),
    addEventListener: (type, listener) => root.addEventListener(type, listener, { signal: controller.signal }),
  };
${engine}
  return () => controller.abort();
}
`;
const destination = new URL("src/lib/zhouyi/", project);
await fs.mkdir(destination, { recursive: true });
await fs.writeFile(new URL("engine.js", destination), engineModule);
await fs.writeFile(new URL("markup.json", destination), `${JSON.stringify(markup)}\n`);
await fs.writeFile(new URL("base.css", destination), `/* Generated by npm run sync:zhouyi. */\n${css.toString()}\n`);
console.log(`Synced Zhouyi blog edition to ${fileURLToPath(destination)}`);
